### ISSUE TITLE
css breaks * {border:0}

### ISSUE THREAD

**Issue by mech01nc01** [bhaveshpatel200/vue3-datatable#47]
i had to change
```css
*,
:after,
:before {
    border: 0 solid #0000;
    box-sizing: border-box
}

```
to 
```css
.bh-table-responsive *,
:after,
:before {
    border: 0 solid #0000;
    box-sizing: border-box
}
```
don't know what it might break with datatable but remving all borders in my page was not an option
